---
- name: Restart gitea
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: gitea
  listen: h_restart-gitea

- name: Restart nginx
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: nginx
  listen: h_restart-nginx